"use client";
import StartDateInput from "@/components/business/start-date-input";
import { enteredDuration, usesDays, WORK_DAY_MINUTES } from "@/domain/duration";
import { useMemo, useState } from "react";
import Link from "next/link";
import MachineRows from "@/components/planning/machine-rows";
import MoldProcessForm from "@/components/business/mold-process-form";
import BatchForm from "@/components/business/batch-form";
import { activePlan } from "@/domain/business";
import { mutateBusiness, SaveOutcomeUnknownError } from "@/lib/business/client";
import { createDemo } from "@/domain/demo";
import { BOM_PROCESSES, PROCESSES, BREAKS, addDays, at, calculateWorkMinutes, dateTimeLabel, fromLocalInput, localInput, minutesLabel, movePriority, overlaps, placeAtRequestedStart, renumber, schedule, taskConflicts, timeLabel } from "@/domain/planning";
import type { PlanData, Task, TaskStatus, WorkLog } from "@/domain/planning";

type Draft = { data: PlanData; revision: number; title: string };
const STATUS: Record<TaskStatus, string> = { pending: "未着手", running: "作業中", completed: "完了" };
function Mark({ symbol }: { symbol: string }) { return <span className="symbol" aria-hidden="true">{symbol}</span>; }
export default function PlanningBoard({ initialData, initialRole="admin", processFilter="", machineFilter="", basePath="/demo", initialDate="2026-09-30" }: { initialData?: PlanData; initialRole?: "admin"|"operator"; processFilter?: string; machineFilter?: string; basePath?: string; initialDate?: string }) {
  const [saveUncertain,setSaveUncertain]=useState(false); const database = Boolean(initialData); const [busy,setBusy]=useState(false); const [batchOpen,setBatchOpen]=useState(false); const [moldOpen,setMoldOpen]=useState(false);
  const [data, setData] = useState<PlanData>(()=>initialData?activePlan(initialData):createDemo());
  const [role, setRole] = useState<"admin" | "operator">(initialRole);
  const [startDate, setStartDate] = useState(initialDate); const [viewDays, setViewDays] = useState(7);
  const [filter, setFilter] = useState(""); const [equipmentFilter, setEquipmentFilter] = useState(machineFilter); const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string | null>(null); const [rowTaskIds,setRowTaskIds]=useState<string[]|null>(null); const [tab, setTab] = useState("plan");
  const [partProductId, setPartProductId] = useState(""); const partProduct = data.products.find((product) => product.id === partProductId);
  const [dialog, setDialog] = useState<"product" | "calendar" | "equipment" | null>(null);
  const [draft, setDraft] = useState<Draft | null>(null); const [acknowledged, setAcknowledged] = useState(false);
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [dirty, setDirty] = useState(Boolean(initialData?.needsRecalculation));
  const days = useMemo(() => Array.from({ length: viewDays }, (_, index) => addDays(startDate, index)), [startDate, viewDays]);
  const dayWidth = viewDays === 1 ? 1728 : viewDays === 3 ? 720 : 336; const timelineWidth = dayWidth * viewDays;
  const windowStart = new Date(at(startDate, 0)).getTime(); const windowEnd = new Date(at(addDays(startDate, viewDays), 0)).getTime();
  const selected = data.tasks.find((task) => task.id === selectedId);
  const selectedMold = selected && data.parts.some(part=>part.id===selected.partId && part.scope==="mold");
  const conflicts = new Set(taskConflicts(data.tasks).flat());
  function productFor(task: Task, source = data) { const part = source.parts.find((item) => item.id === task.partId)!; return source.products.find((item) => item.id === part.productId)!; }
  function late(task: Task, source = data) { return new Date(task.plannedEnd).getTime() >= new Date(at(addDays(productFor(task, source).dueDate, 1), 0)).getTime(); }
  const lateCount = data.parts.filter((part) => data.tasks.some((task) => task.partId === part.id && late(task))).length;
  function fail(cause: unknown) { if(cause instanceof SaveOutcomeUnknownError)setSaveUncertain(true); setError(cause instanceof Error ? cause.message : "処理に失敗しました。入力を確認してください。"); }
  function preview(candidate: PlanData, title: string, manualId?: string) {
    try { const original = candidate.tasks.find((task) => task.id === manualId); const input = original ? { ...candidate, tasks: candidate.tasks.map((task) => task.id === manualId ? { ...placeAtRequestedStart(task, candidate.calendar), fixed: true, manualOverride: true } : task) } : candidate; const scheduled = schedule(input).map((task) => original && task.id === manualId ? { ...task, fixed: original.fixed, manualOverride: original.fixed } : task); setDraft({ data: { ...candidate, tasks: scheduled }, revision: candidate.revision, title }); setAcknowledged(false); setError(""); }
    catch (cause) { fail(cause); }
  }
  async function commit() {
    if (!draft || role !== "admin" || busy || saveUncertain) return;
    if (draft.revision !== data.revision) { setDraft(null); setError("実績や予定が更新されました。最新データで再計算してください。"); return; }
    if (taskConflicts(draft.data.tasks).length && !acknowledged) { setError("設備の重複を確認してください。"); return; }
    if(!dirty && JSON.stringify(draft.data.parts)===JSON.stringify(data.parts) && JSON.stringify(draft.data.tasks)===JSON.stringify(data.tasks)){setDraft(null);setNotice("変更が必要な予定はありません。");return;}
    setBusy(true); try { const saved=database?activePlan(await mutateBusiness("plan",data.revision,{parts:draft.data.parts,tasks:draft.data.tasks},undefined,acknowledged)):{...draft.data,revision:data.revision+1};setData(saved);setDraft(null);setDirty(false);setNotice(database?"日程をDBに保存しました":"日程を確定しました。このデモの実行中のみ保持されます。"); } catch(cause){fail(cause);} finally{setBusy(false);}
  }
  function saveTask(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected || role !== "admin") return;
    try {
      const form = new FormData(event.currentTarget); const equipmentId = selectedMold ? "" : String(form.get("equipment"));
      let tasks = data.tasks.map((task) => task.id === selected.id ? { ...task, equipmentId, pressNo: selectedMold ? String(form.get("pressNo") ?? "").trim() : task.pressNo, workerId: String(form.get("worker")), duration: enteredDuration(selected.process,Number(form.get("duration"))), earliestStart: fromLocalInput(String(form.get("earliest"))), overnight: form.get("overnight") === "on", breakRun: form.get("breakRun") === "on", fixed: form.get("fixed") === "on" } : task);
      if (!selectedMold) { tasks = renumber(tasks, selected.equipmentId); tasks = renumber(tasks, equipmentId); tasks = movePriority(tasks, selected.id, Number(form.get("priority"))); }
      const manual = (event.nativeEvent as SubmitEvent).submitter?.getAttribute("value") === "manual"; preview({ ...data, tasks }, manual ? (selectedMold ? "単体工程の手動配置" : "設備重複を許可した手動配置") : "工程予定の変更", manual ? selected.id : undefined);
    } catch (cause) { fail(cause); }
  }
  async function saveActual(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected || busy || saveUncertain) return; setBusy(true);
    try {
      const form = new FormData(event.currentTarget); const start = fromLocalInput(String(form.get("start"))); const end = fromLocalInput(String(form.get("end")));
      const workerId = String(form.get("worker")); const oldLogId = String(form.get("logId") || "");
      const originalLog = data.logs.find((item) => item.id === oldLogId); const breakSnapshot = originalLog?.breaks ?? BREAKS; const calculatedMinutes = calculateWorkMinutes(start, end, breakSnapshot); const overrideText = String(form.get("override")); const overrideMinutes = overrideText === "" ? undefined : Number(overrideText);
      if (overrideMinutes !== undefined && (!Number.isInteger(overrideMinutes) || overrideMinutes < 0)) throw new Error("修正時間は0以上の整数分で入力してください。");
      if (data.logs.some((log) => log.id !== oldLogId && log.workerId === workerId && overlaps(log, { start, end })) && form.get("acceptOverlap") !== "on") throw new Error("同じ作業者の実績が重複しています。重複を確認してチェックしてください。");
      const status = String(form.get("status")) as TaskStatus;
      const log: WorkLog = { id: oldLogId || crypto.randomUUID(), taskId: selected.id, workerId, start, end, calculatedMinutes, overrideMinutes, reason: String(form.get("reason")), breaks: breakSnapshot.map(([a, b]) => [a, b]), editedBy: role === "admin" ? "管理者（デモ）" : "担当者（デモ）" };
      const logs = oldLogId ? data.logs.map((item) => item.id === oldLogId ? log : item) : [...data.logs, log]; const related = logs.filter((item) => item.taskId === selected.id);
      let tasks = data.tasks.map((task) => task.id === selected.id ? { ...task, status, actualStart: related.map((item) => item.start).sort()[0], actualEnd: status === "completed" ? related.map((item) => item.end).sort().at(-1)! : undefined } : task);
      tasks = renumber(tasks, selected.equipmentId); const candidate = { ...data, logs, tasks, revision: data.revision + 1 };
      const persisted=database?activePlan(await mutateBusiness("actual",data.revision,{...log,overrideMinutes:log.overrideMinutes??null,status,acceptOverlap:form.get("acceptOverlap")==="on"})):candidate;
      setData(persisted); setDirty(true); setNotice("実績を記録しました。再計算した日程は管理者が確認して確定します。"); preview(persisted, "実績に合わせた後工程の再計算");
    } catch (cause) { fail(cause); } finally {setBusy(false);}
  }
  function addProduct(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (role !== "admin") return;
    try {
      const form = new FormData(event.currentTarget); const name = String(form.get("name")).trim(); const partName = String(form.get("partName")).trim(); const quantity = Number(form.get("quantity")); const dueDate = String(form.get("dueDate"));
      if (!name || !partName || !dueDate || !Number.isInteger(quantity) || quantity < 1) throw new Error("製品名・パーツ名・数量・納期を入力してください。");
      const existingId = String(form.get("productId") || ""); const existingProduct = data.products.find((product) => product.id === existingId); if (existingId && !existingProduct) throw new Error("製品を選択してください。"); const productId = existingProduct?.id ?? crypto.randomUUID(), partId = crypto.randomUUID(); const earliestStart = fromLocalInput(String(form.get("earliest"))); const urgent = form.get("urgent") === "on"; let tasks = [...data.tasks];
      for (const process of BOM_PROCESSES) {
        const equipmentId = String(form.get(`equipment-${process.code}`));
        const task: Task = { id: crypto.randomUUID(), partId, process: process.code, equipmentId, workerId: String(form.get(`worker-${process.code}`)), duration: enteredDuration(process.code,Number(form.get(`duration-${process.code}`))), earliestStart, priority: tasks.filter((item) => item.equipmentId === equipmentId && item.status === "pending").length + 1, status: "pending", overnight: form.get(`overnight-${process.code}`) === "on", breakRun: false, fixed: false, plannedStart: "", plannedEnd: "", segments: [] };
        tasks.push(task); if (urgent) tasks = movePriority(tasks, task.id, Number(form.get("urgentRank")));
      }
      preview({ ...data, products: existingProduct ? data.products : [...data.products, { id: productId, name, customer: String(form.get("customer")), dueDate, notes: String(form.get("notes")) }], parts: [...data.parts, { id: partId, productId, name: partName, quantity, drawingNumber: String(form.get("drawing")), processes: BOM_PROCESSES.map(process=>process.code) }], tasks }, urgent ? "飛び込みタスクの挿入" : "製品・パーツの新規予定");
      setDialog(null);
    } catch (cause) { fail(cause); }
  }
  const month = startDate.slice(0, 7); const monthLength = new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate();
  async function saveCalendar(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (role !== "admin") return;
    const form = new FormData(event.currentTarget); const calendar = { ...data.calendar };
    for (let index = 1; index <= monthLength; index++) { const day = `${month}-${String(index).padStart(2, "0")}`; calendar[day] = form.get(day) === "on"; }
    try{const candidate=database?activePlan(await mutateBusiness("master",data.revision,{days:Object.entries(calendar).filter(([day])=>day.startsWith(month)).map(([date,working])=>({date,working}))},"calendar")):{...data,calendar,revision:data.revision+1};setData(candidate);setDialog(null);setDirty(true);preview(candidate,"会社カレンダー変更後の予定");}catch(cause){fail(cause);}
  }
  const filtered = data.tasks.filter((task) => { const product = productFor(task); const part = data.parts.find((item) => item.id === task.partId)!; return (!processFilter || task.process===processFilter) && (!machineFilter || task.equipmentId===machineFilter) && (!filter || product.id === filter) && (!equipmentFilter || task.equipmentId === equipmentFilter) && (!query || `${product.name} ${part.name} ${product.customer}`.includes(query)); });
  const groups = data.products.map(product=>({product,tasks:filtered.filter(task=>data.parts.some(part=>part.id===task.partId&&part.productId===product.id)).sort((a,b)=>PROCESSES.findIndex(process=>process.code===a.process)-PROCESSES.findIndex(process=>process.code===b.process))})).filter(group=>group.tasks.length);
  const changes = draft?.data.tasks.filter((task) => { const old = data.tasks.find((item) => item.id === task.id); return !old || JSON.stringify(old) !== JSON.stringify(task); }) ?? [];
  return <div className="app-shell">{busy&&<div className="saving-overlay" role="status">保存しています…</div>}{moldOpen&&<MoldProcessForm data={data} startDate={startDate} onPreview={preview} onClose={()=>setMoldOpen(false)} />}{batchOpen&&<BatchForm data={data} startDate={startDate} onPreview={preview} onClose={()=>setBatchOpen(false)} />}
    <aside className="sidebar"><div className="brand-mark">▦</div><div className="brand-text">K<span>PLAN</span></div><Link className="nav-item active" href={basePath}><Mark symbol="▤" /><span>計画</span></Link><Link className="nav-item" href={`${basePath}/equipment`}><Mark symbol="▥" /><span>設備</span></Link><Link className="nav-item" href={`${basePath}/calendar`}><Mark symbol="▦" /><span>稼働日</span></Link><Link className="nav-item" href={`${basePath}/products`}><span>金型</span></Link><Link className="nav-item" href={`${basePath}/bom`}><span>BOM</span></Link><Link className="nav-item" href={`${basePath}/users`}><span>利用者</span></Link><div className="sidebar-bottom"><div className="avatar">{role === "admin" ? "管" : "担"}</div><span>{database?"DB":"DEMO"}</span></div></aside>
    <div className="workspace"><header className="app-header"><div className="breadcrumb">生産管理 <span>/</span> <strong>生産計画</strong></div><div className="header-right"><span className="live-dot" />{database?"DB接続":"デモモード"}{!database&&<select aria-label="デモの操作権限" value={role} onChange={(event) => { setRole(event.target.value as "admin" | "operator"); setTab(event.target.value === "operator" ? "actual" : "plan"); }}><option value="admin">管理者として操作</option><option value="operator">工程担当者として操作</option></select>}<Link href="/login" className="header-login">ログイン</Link></div></header>
    <main className="main-content"><div className="page-heading"><div><div className="eyebrow">PRODUCTION PLANNING</div><h1>{machineFilter?`${data.equipment.find(x=>x.id===machineFilter)?.name??"機械"} 加工予定`:processFilter?`${PROCESSES.find(x=>x.code===processFilter)?.name??"工程"} 工程予定`:"金型別 生産計画"}</h1><p>パーツの加工と金型単位の型組・トライを、ひとつの時間軸で。</p></div><div className="row-actions"><button className="button primary" disabled={role !== "admin"} onClick={() => database?setBatchOpen(true):setDialog("product")}>＋ BOMから予定を追加</button><button className="button" disabled={role !== "admin"} onClick={()=>setMoldOpen(true)}>＋ 型組・トライを登録</button></div></div>
    <div className="demo-banner">{database?"Supabaseのデータを表示しています。予定変更はプレビュー後に確定してください。":"ⓘ 確認用デモです。変更は再読み込みで消えます。"}</div>
    <div className="summary-grid">{[{ label: "計画中の金型", value: data.products.length, unit: "件", note: `${data.parts.filter(part=>part.scope !== "mold").length}パーツ`, icon: "▦", color: "green" }, { label: "未着手の工程", value: data.tasks.filter((task) => task.status === "pending").length, unit: "件", note: `全${data.tasks.length}工程`, icon: "◷", color: "blue" }, { label: "完了した工程", value: data.tasks.filter((task) => task.status === "completed").length, unit: "件", note: "状態で進捗を管理", icon: "✓", color: "purple" }, { label: "納期超過の予定", value: lateCount, unit: "パーツ", note: lateCount ? "日程の確認が必要" : "超過なし", icon: "!", color: "amber" }].map((stat) => <div className="summary-card" key={stat.label}><div className={`stat-icon ${stat.color}`}>{stat.icon}</div><div><span>{stat.label}</span><strong>{stat.value}<small>{stat.unit}</small></strong></div><div className="stat-note">{stat.note}</div></div>)}</div>
    {error && <div className="message error" role="alert">⚠ {error}{saveUncertain && <button className="button" onClick={()=>window.location.reload()}>再読み込みして保存結果を確認</button>}<button onClick={() => setError("")} aria-label="エラーを閉じる">×</button></div>}{notice && <div className="message success" role="status">✓ {notice}<button onClick={() => setNotice("")} aria-label="通知を閉じる">×</button></div>}{dirty && <div className="recalculate-banner"><span>実績・カレンダーを反映した日程を管理者が確認してください。</span><button className="button small" disabled={role !== "admin"} onClick={() => preview(data, "最新データから再計算")}>↻ 再計算</button></div>}
    <section className="planning-card"><div className="chart-toolbar"><div className="date-controls"><button className="icon-button" aria-label="前の期間" onClick={() => setStartDate(addDays(startDate, -viewDays))}>‹</button><input aria-label="表示開始日" type="date" value={startDate} onChange={(event) => event.target.value && setStartDate(event.target.value)} /><button className="icon-button" aria-label="次の期間" onClick={() => setStartDate(addDays(startDate, viewDays))}>›</button><button className="today-button" onClick={() => setStartDate(database?new Date(Date.now()+9*3600000).toISOString().slice(0,10):"2026-09-30")}>{database?"今日":"デモ基準日"}</button></div><div className="view-switch">{[1, 3, 7].map((count) => <button key={count} className={viewDays === count ? "selected" : ""} onClick={() => setViewDays(count)}>{count === 7 ? "1週間" : `${count}日`}</button>)}</div><button className="button small" disabled={role !== "admin"} onClick={() => preview(data, "全体の自動調整")}>↻ 自動調整</button></div>
    <div className="filter-toolbar"><input className="search-field" aria-label="製品・パーツを検索" placeholder="製品名・パーツ名・取引先で検索" value={query} onChange={(event) => setQuery(event.target.value)} /><select aria-label="製品の絞り込み" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">すべての製品</option>{data.products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select><select aria-label="設備の絞り込み" disabled={Boolean(machineFilter)} value={equipmentFilter} onChange={(event) => setEquipmentFilter(event.target.value)}><option value="">すべての設備</option>{data.equipment.map((machine) => <option key={machine.id} value={machine.id}>{machine.name}</option>)}</select><span className="row-count">{filtered.length}工程</span></div>
    <div className="gantt-scroll"><div className="gantt-inner" style={{ width: timelineWidth + 490 }}><div className="gantt-heading"><div className="frozen heading-columns"><span>金型 / パーツ / 工程</span><span>設備 / 使用プレスNo</span><span>担当</span><span>加工順</span></div><div className="date-heading" style={{ width: timelineWidth }}>{days.map((day) => <div key={day} className={`day-heading ${!data.calendar[day] ? "off-day" : ""}`} style={{ width: dayWidth }}><div><strong>{Number(day.slice(5, 7))}/{Number(day.slice(8))}</strong><span>{["日", "月", "火", "水", "木", "金", "土"][new Date(`${day}T12:00:00+09:00`).getUTCDay()]}</span>{day === "2026-09-30" && <em>基準日</em>}{!data.calendar[day] && <em>{day in data.calendar ? "休日" : "未設定"}</em>}</div><div className="hour-heading">{Array.from({ length: viewDays === 1 ? 48 : viewDays === 3 ? 24 : 8 }, (_, index) => <span key={index}>{viewDays === 1 ? `${Math.floor(index / 2)}:${index % 2 ? "30" : "00"}` : `${index * (viewDays === 3 ? 1 : 3)}:00`}</span>)}</div></div>)}</div></div>
    {groups.map(({ product, tasks }) => <div key={product.id}><div className="part-group"><div className="frozen part-heading"><span className="part-dot" /><Link href={`${basePath}/products/${product.id}`}><strong>{product.name}</strong></Link><span>{new Set(tasks.filter(task=>data.parts.find(part=>part.id===task.partId)?.scope !== "mold").map(task=>task.partId)).size}パーツ / {tasks.length}工程</span></div><div className="part-meta" style={{ width: timelineWidth }}><span>{product.customer || "取引先未登録"}</span><span>金型単位</span><span>納期 {product.dueDate.slice(5).replace("-", "/")}</span></div></div><MachineRows tasks={tasks} data={data} days={days} dayWidth={dayWidth} timelineWidth={timelineWidth} windowStart={windowStart} windowEnd={windowEnd} selectedId={selectedId} conflicts={conflicts} basePath={basePath} onSelect={id=>{setSelectedId(id);setTab(role==="operator"?"actual":"plan");setError("");}} onList={setRowTaskIds} /></div>)}{!groups.length && <div className="empty-state">条件に一致する工程はありません。</div>}</div></div>
    <footer className="chart-footer"><div className="legend">{PROCESSES.map((process) => <Link key={process.code} href={`${basePath}/process/${process.code}`}><i style={{ background: process.color }} />{process.name}</Link>)}</div><span>◷ 8:50–17:40 / 実働7時間50分</span></footer></section><p className="bottom-note">工程名・機械名から詳細画面へ移動できます。バーをクリックすると予定・実績を編集できます。時間軸は横にスクロールできます。休日は会社カレンダーの設定です。</p></main></div>
    {rowTaskIds && <div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="加工予定一覧"><div className="panel-header"><h2>加工予定一覧</h2><button className="icon-button" aria-label="閉じる" onClick={()=>setRowTaskIds(null)}>×</button></div><div className="machine-task-list">{rowTaskIds.map(id=>{const task=data.tasks.find(task=>task.id===id);if(!task)return null;const part=data.parts.find(part=>part.id===task.partId)!;return <button key={id} className="button" onClick={()=>{setSelectedId(id);setRowTaskIds(null);setTab(role==="operator"?"actual":"plan");setError("");}}><strong>{part.name}</strong><span>{dateTimeLabel(task.plannedStart)} ～ {dateTimeLabel(task.plannedEnd)}</span><small>{STATUS[task.status]} / {data.workers.find(worker=>worker.id===task.workerId)?.name}{task.equipmentId?` / 加工順 ${task.priority}`:""}</small></button>;})}</div></section></div>}
    {selected && <div className="panel-overlay" onClick={() => setSelectedId(null)}><aside className="detail-panel" onClick={(event) => event.stopPropagation()}><div className="panel-header"><div><div className="eyebrow">TASK DETAIL</div><h2>{PROCESSES.find((process) => process.code === selected.process)?.name}</h2></div><button className="icon-button" aria-label="工程詳細を閉じる" onClick={() => setSelectedId(null)}>×</button></div><div className="task-context"><strong>{productFor(selected).name}</strong><span>{data.parts.find((part) => part.id === selected.partId)?.name}</span><span className={`status-chip ${selected.status}`}>{STATUS[selected.status]}</span></div><div className="panel-tabs"><button className={tab === "plan" ? "active" : ""} onClick={() => setTab("plan")}>予定</button><button className={tab === "actual" ? "active" : ""} onClick={() => setTab("actual")}>実績入力</button></div><div className="panel-body">{error && <div className="inline-error" role="alert">{error}</div>}
    {tab === "plan" ? <form key={`${selected.id}-${data.revision}`} onSubmit={saveTask}><div className="plan-period"><span>現在の予定</span><strong>{dateTimeLabel(selected.plannedStart)}</strong><span>↓</span><strong>{dateTimeLabel(selected.plannedEnd)}</strong></div><fieldset disabled={role !== "admin" || selected.status !== "pending"}>{selectedMold ? <label>使用プレスNo<input name="pressNo" defaultValue={selected.pressNo ?? ""} maxLength={40} placeholder="未定の場合は空欄" /></label> : <label>設備<select name="equipment" defaultValue={selected.equipmentId}>{data.equipment.filter((item) => item.process === selected.process).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>担当者<select name="worker" defaultValue={selected.workerId}>{data.workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><div className="form-row"><label>{usesDays(selected.process) ? "所要日数（日）" : "所要時間（分）"}<input name="duration" type="number" min={usesDays(selected.process) ? 1 : 30} step={usesDays(selected.process) ? 1 : 30} defaultValue={usesDays(selected.process) ? Math.ceil(selected.duration / WORK_DAY_MINUTES) : selected.duration} required /></label>{!selectedMold && <label>機械内の加工順<input name="priority" type="number" min="1" step="1" defaultValue={selected.priority} required /></label>}</div><label>開始可能日時<StartDateInput name="earliest" defaultValue={localInput(selected.earliestStart)} required /></label><label className="checkbox"><input name="fixed" type="checkbox" defaultChecked={selected.fixed} />予定を固定する</label>{usesDays(selected.process) ? <p className="help-text">1日＝実働7時間50分。休日・休憩を除いて計算します。{selected.duration % WORK_DAY_MINUTES !== 0 && `旧予定は${selected.duration}分です。保存すると入力した日数に変更します。`}</p> : <label className="checkbox"><input name="breakRun" type="checkbox" defaultChecked={selected.breakRun} />休憩中も設備を稼働する</label>}{!["assembly", "trial"].includes(selected.process) && <label className="checkbox"><input name="overnight" type="checkbox" defaultChecked={selected.overnight} />夜間・休日も継続稼働する</label>}<button className="button primary full-width" type="submit" value="auto">↻ 変更後の日程を確認</button><button className="button full-width" type="submit" value="manual">{selectedMold ? "指定開始で手動配置" : "指定開始で手動配置（設備重複を許可）"}</button></fieldset>{(role !== "admin" || selected.status !== "pending") && <p className="help-text">予定編集は管理者のみです。作業中・完了済みの予定は維持します。</p>}</form> : <ActualForm key={`${selected.id}-${data.revision}`} task={selected} data={data} onSubmit={saveActual} />}</div></aside></div>}
    {dialog && <div className="modal-overlay" onClick={() => setDialog(null)}><section className={`modal ${dialog === "product" ? "wide-modal" : ""}`} role="dialog" aria-modal="true" aria-label={dialog === "product" ? "製品・パーツの追加" : dialog === "calendar" ? "会社カレンダー" : "設備一覧"} onClick={(event) => event.stopPropagation()}><div className="panel-header"><div><div className="eyebrow">{dialog === "product" ? "NEW PRODUCTION" : "SETTINGS"}</div><h2>{dialog === "product" ? "製品・パーツを追加" : dialog === "calendar" ? "会社カレンダー" : "設備一覧"}</h2></div><button className="icon-button" onClick={() => setDialog(null)} aria-label="ダイアログを閉じる">×</button></div>{error && <div className="inline-error">{error}{saveUncertain && <button className="button" onClick={()=>window.location.reload()}>再読み込みして保存結果を確認</button>}</div>}
    {dialog === "product" && <form key={partProductId} onSubmit={addProduct}><label>登録先の製品<select name="productId" value={partProductId} onChange={(event) => setPartProductId(event.target.value)}><option value="">新しい製品を登録</option>{data.products.map((product) => <option key={product.id} value={product.id}>{product.name}にパーツを追加</option>)}</select></label><div className="form-row"><label>製品名 <em>必須</em><input name="name" required maxLength={120} defaultValue={partProduct?.name ?? ""} readOnly={Boolean(partProduct)} /></label><label>取引先<input name="customer" maxLength={120} defaultValue={partProduct?.customer ?? ""} readOnly={Boolean(partProduct)} /></label></div><div className="form-row"><label>パーツ名 <em>必須</em><input name="partName" required maxLength={120} /></label><label>図番<input name="drawing" maxLength={100} /></label></div><div className="form-row three"><label>数量 <em>必須</em><input name="quantity" type="number" defaultValue={1} min={1} step={1} required /></label><label>納期 <em>必須</em><input name="dueDate" type="date" defaultValue={partProduct?.dueDate ?? addDays(startDate, 7)} readOnly={Boolean(partProduct)} required /></label><label>開始可能日時<StartDateInput name="earliest" defaultValue={localInput(at(startDate, 530))} required /></label></div><label>備考<input name="notes" maxLength={500} defaultValue={partProduct?.notes ?? ""} readOnly={Boolean(partProduct)} /></label><label className="checkbox urgent-checkbox"><input name="urgent" type="checkbox" />飛び込みとして設備の順番に挿入する</label><label>飛び込みの挿入順位（各設備）<input name="urgentRank" type="number" min={1} step={1} defaultValue={1} required /></label><h3>加工工程の予定条件</h3><div className="process-form-list">{BOM_PROCESSES.map((process, index) => <div key={process.code} className="process-form-row"><strong><i style={{ background: process.color }} />{process.name}</strong><label>設備<select name={`equipment-${process.code}`}>{data.equipment.filter((item) => item.process === process.code).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>担当者<select name={`worker-${process.code}`}>{data.workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><label>{usesDays(process.code)?"所要日数（日）":"所要時間（分）"}<input name={`duration-${process.code}`} type="number" min={usesDays(process.code)?1:30} step={usesDays(process.code)?1:30} defaultValue={usesDays(process.code)?1:[180,120,180][index]} required /></label><label className="checkbox night-checkbox"><input name={`overnight-${process.code}`} type="checkbox" disabled={index > 2} />夜間</label></div>)}</div><div className="modal-actions"><button className="button" type="button" onClick={() => setDialog(null)}>キャンセル</button><button className="button primary" type="submit">日程を自動計算 →</button></div></form>}
    {dialog === "calendar" && <form onSubmit={saveCalendar}><p className="help-text">チェックした日が稼働日です。未設定の日は自動計算できません。</p><h3>{month.replace("-", "年")}月</h3><div className="calendar-grid">{Array.from({ length: monthLength }, (_, index) => { const day = `${month}-${String(index + 1).padStart(2, "0")}`; return <label key={day} className="calendar-day"><input type="checkbox" name={day} defaultChecked={data.calendar[day]} disabled={role !== "admin"} /><span>{index + 1}<small>{["日", "月", "火", "水", "木", "金", "土"][new Date(`${day}T12:00:00+09:00`).getUTCDay()]}</small></span></label>; })}</div><div className="work-hours"><strong>勤務 8:50–17:40</strong><span>昼休み 12:00–12:50 / 休憩 15:00–15:10</span></div><button className="button primary full-width" type="submit" disabled={role !== "admin"}>カレンダーを反映して予定を確認</button></form>}
    {dialog === "equipment" && <><p className="help-text">画面確認用の設備です。実際の設備・担当者はDB接続後に登録します。</p><div className="equipment-list">{PROCESSES.map((process) => <div key={process.code}><strong><i style={{ background: process.color }} />{process.name}</strong><span>{data.equipment.filter((item) => item.process === process.code).map((item) => item.name).join(" / ")}</span></div>)}</div><h3>担当者（デモ）</h3><div className="worker-list">{data.workers.map((worker) => <span key={worker.id}>{worker.name.replace("（デモ）", "")}</span>)}</div></>}
    </section></div>}
    {draft && <div className="modal-overlay preview-overlay"><section className="modal wide-modal" role="dialog" aria-modal="true" aria-label="日程変更のプレビュー"><div className="panel-header"><div><div className="eyebrow">SCHEDULE PREVIEW</div><h2>{draft.title}</h2></div><button className="icon-button" aria-label="プレビューを閉じる" onClick={() => setDraft(null)}>×</button></div><p className="help-text">{changes.length}工程の変更案です。作業中・完了済み・固定予定は維持しています。</p><div className="preview-table"><table><thead><tr><th>金型 / パーツ / 工程</th><th>変更前</th><th>変更後</th><th>納期</th></tr></thead><tbody>{changes.map((task) => { const old = data.tasks.find((item) => item.id === task.id); const part = draft.data.parts.find((item) => item.id === task.partId)!; const product = productFor(task, draft.data); return <tr key={task.id}><td><strong>{product.name}</strong><small>{part.name} · {PROCESSES.find((item) => item.code === task.process)?.name}</small></td><td>{old ? <>{dateTimeLabel(old.plannedStart)}<small>〜 {dateTimeLabel(old.plannedEnd)}</small></> : "新規"}</td><td><strong>{dateTimeLabel(task.plannedStart)}</strong><small>〜 {dateTimeLabel(task.plannedEnd)}</small></td><td><span className={late(task, draft.data) ? "late-label" : "on-time"}>{late(task, draft.data) ? "納期超過" : "納期内"}</span></td></tr>; })}</tbody></table>{!changes.length && <div className="empty-state">変更が必要な予定はありません。</div>}</div>{taskConflicts(draft.data.tasks).length > 0 && <label className="checkbox conflict-confirm"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} />設備の重複 {taskConflicts(draft.data.tasks).length}件を確認して保存する</label>}{error && <div className="inline-error">{error}{saveUncertain && <button className="button" onClick={()=>window.location.reload()}>再読み込みして保存結果を確認</button>}</div>}<div className="modal-actions"><button className="button" onClick={() => setDraft(null)}>予定変更を取消</button><button className="button primary" onClick={commit} disabled={busy || saveUncertain || role !== "admin" || (taskConflicts(draft.data.tasks).length > 0 && !acknowledged)}>{role === "admin" ? "✓ 確認して日程を確定" : "管理者の確認が必要"}</button></div></section></div>}
  </div>;
}
function ActualForm({ task, data, onSubmit }: { task: Task; data: PlanData; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void }) {
  const logs = data.logs.filter((log) => log.taskId === task.id); const [logId, setLogId] = useState(""); const log = logs.find((item) => item.id === logId);
  const [start, setStart] = useState(localInput(task.actualStart ?? task.plannedStart)); const [end, setEnd] = useState(localInput(task.actualEnd ?? task.plannedEnd));
  let calculated = "—"; try { calculated = minutesLabel(calculateWorkMinutes(fromLocalInput(start), fromLocalInput(end), log?.breaks ?? BREAKS)); } catch { /* 入力途中は未計算。保存時に入力を検証する。 */ }
  function chooseLog(value: string) { setLogId(value); const selected = logs.find((item) => item.id === value); setStart(localInput(selected?.start ?? task.plannedStart)); setEnd(localInput(selected?.end ?? task.plannedEnd)); }
  return <form key={logId} onSubmit={onSubmit}><input type="hidden" name="logId" value={logId} />{logs.length > 0 && <label>新規追加 / 修正<select value={logId} onChange={(event) => chooseLog(event.target.value)}><option value="">新しい作業実績を追加</option>{logs.map((item) => <option key={item.id} value={item.id}>{dateTimeLabel(item.start)} の実績を修正</option>)}</select></label>}<label>実際の作業者<select name="worker" defaultValue={log?.workerId ?? task.workerId}>{data.workers.map((worker) => <option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label><label>状態<select name="status" defaultValue={task.status === "pending" ? "running" : task.status}><option value="running">作業中</option><option value="completed">完了</option></select></label><label>実際の開始時刻<input type="datetime-local" name="start" value={start} onInput={(event) => setStart(event.currentTarget.value)} onChange={(event) => setStart(event.target.value)} required /></label><label>実際の終了時刻<input type="datetime-local" name="end" value={end} onInput={(event) => setEnd(event.currentTarget.value)} onChange={(event) => setEnd(event.target.value)} required /></label><div className="calculated-time"><span>休憩を除いた作業時間</span><strong>{calculated}</strong><small>無人稼働時間は自動加算しません。</small></div><label>作業時間の修正（分・任意）<input name="override" type="number" min={0} step={1} defaultValue={log?.overrideMinutes ?? ""} placeholder="空欄なら自動計算値" /></label><label>修正理由（任意）<input name="reason" defaultValue={log?.reason ?? ""} maxLength={500} /></label><label className="checkbox"><input type="checkbox" name="acceptOverlap" />実績の重複を確認して保存する</label><button className="button primary full-width" type="submit">✓ {log ? "実績を修正して再計算" : "実績を記録して再計算"}</button>{logs.length > 0 && <div className="log-history"><h3>登録済み実績</h3>{logs.map((item) => <div key={item.id}><strong>{dateTimeLabel(item.start)} 〜 {timeLabel(item.end)}</strong><span>{minutesLabel(item.overrideMinutes ?? item.calculatedMinutes)} / {data.workers.find((worker) => worker.id === item.workerId)?.name}</span><small>更新者: {item.editedBy}</small></div>)}</div>}</form>;
}
