"use client";
import StartDateInput from "@/components/business/start-date-input";
import { enteredDuration, usesDays } from "@/domain/duration";
import { useState } from "react";
import { bomProcessCatalog, at, fromLocalInput, localInput, movePriority, type PlanData, type Task } from "@/domain/planning";
import { remainingQuantity } from "@/domain/business";
export default function BatchForm({data,startDate,onPreview,onClose}:{data:PlanData;startDate:string;onPreview:(data:PlanData,title:string)=>void;onClose:()=>void}){
 const [productId,setProductId]=useState(data.products[0]?.id??"");const [bomId,setBomId]=useState("");const [error,setError]=useState("");
 const BOM_PROCESSES=bomProcessCatalog(data);const item=data.bom?.find(x=>x.id===bomId);const remaining=remainingQuantity(data,bomId);
 function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();try{
  if(!item||item.archived)throw new Error("BOM項目を選択してください");const form=new FormData(event.currentTarget);const quantity=Number(form.get("quantity"));
  if(!Number.isInteger(quantity)||quantity<1||quantity>remaining)throw new Error("未登録数量の範囲で入力してください");
  const partId=crypto.randomUUID();let tasks=[...data.tasks];const earliestStart=fromLocalInput(String(form.get("earliest")));
  for(const code of item.processes.filter(code=>BOM_PROCESSES.some(p=>p.code===code))){const equipmentId=String(form.get(`equipment-${code}`));const task:Task={id:crypto.randomUUID(),partId,process:code,equipmentId,workerId:String(form.get(`worker-${code}`)),duration:enteredDuration(code,Number(form.get(`duration-${code}`))),earliestStart,priority:tasks.filter(x=>x.equipmentId===equipmentId&&x.status==="pending").length+1,status:"pending",overnight:form.get(`night-${code}`)==="on",breakRun:form.get(`break-${code}`)==="on",fixed:false,plannedStart:"",plannedEnd:"",segments:[]};tasks.push(task);if(form.get("urgent")==="on")tasks=movePriority(tasks,task.id,Number(form.get("rank")));}
  onPreview({...data,parts:[...data.parts,{id:partId,productId,bomId:item.id,name:item.name,quantity,drawingNumber:"",processes:item.processes.filter(code=>BOM_PROCESSES.some(p=>p.code===code))}],tasks},"BOMから製作ロットを追加");onClose();
 }catch(cause){setError(cause instanceof Error?cause.message:"入力を確認してください");}}
 return <div className="modal-overlay"><section className="modal wide-modal" role="dialog" aria-modal="true" aria-label="BOMから予定を登録"><div className="panel-header"><h2>BOMから予定を登録</h2><button className="icon-button" onClick={onClose} aria-label="閉じる">×</button></div>{error&&<div className="inline-error" role="alert">{error}</div>}<form onSubmit={submit}><label>金型<select value={productId} onChange={e=>{setProductId(e.target.value);setBomId("");}} required><option value="">選択してください</option>{data.products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>BOM項目<select value={bomId} onChange={e=>setBomId(e.target.value)} required><option value="">選択してください</option>{data.bom?.filter(x=>x.productId===productId&&!x.archived).map(x=><option key={x.id} value={x.id} disabled={remainingQuantity(data,x.id)<=0}>{x.name} / 未登録 {remainingQuantity(data,x.id)}個</option>)}</select></label>{item&&<><p className="help-text">必要 {item.quantity}個 / 登録済み {item.quantity-remaining}個 / 未登録 {remaining}個</p><label>今回の製作数量<input name="quantity" type="number" min={1} max={remaining} defaultValue={1} required /></label><label>開始可能日時<StartDateInput data={data} name="earliest" defaultValue={localInput(at(startDate,530))} required /></label><label className="checkbox"><input name="urgent" type="checkbox" />飛び込みで挿入</label><label>機械ごとの挿入加工順<input name="rank" type="number" min={1} defaultValue={1} /></label>{BOM_PROCESSES.filter(x=>item.processes.includes(x.code)).map(x=><fieldset key={x.code}><legend>{x.name}</legend><div className="form-row"><label>設備<select name={`equipment-${x.code}`} required>{data.equipment.filter(e=>e.active!==false&&e.process===x.code).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>担当者<select name={`worker-${x.code}`} required>{data.workers.filter(w=>w.active!==false).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label>{usesDays(x.code)?"所要日数（日）":"所要時間（分）"}<input name={`duration-${x.code}`} type="number" min={usesDays(x.code)?1:30} step={usesDays(x.code)?1:30} defaultValue={usesDays(x.code)?1:60} required /></label></div>{usesDays(x.code)?<p className="help-text">1日＝実働7時間50分。休日・休憩を除いて計算します。</p>:<label className="checkbox"><input name={`break-${x.code}`} type="checkbox" />休憩中も稼働</label>}{["machining","grinding","wire"].includes(x.code)&&<label className="checkbox"><input name={`night-${x.code}`} type="checkbox" />夜間・休日も継続稼働</label>}</fieldset>)}</>}<div className="modal-actions"><button type="button" className="button" onClick={onClose}>取消</button><button className="button primary" disabled={!item||remaining<=0}>日程を計算して確認</button></div></form></section></div>;
}
