"use client";
import { useState } from "react";
import LoginUserForm from "./login-user-form";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { PROCESSES, type PlanData, type BomItem, type Product, type Equipment, type Worker, type Part, minutesLabel, workMinutesByDay } from "@/domain/planning";
import { mutateBusiness } from "@/lib/business/client";
import { remainingQuantity } from "@/domain/business";
type Entity="product"|"bom"|"equipment"|"user"|"part";
type EditRow=Partial<Product&BomItem&Equipment&Worker&Part>;
const titles:Record<string,string>={products:"金型管理",bom:"BOM設定",equipment:"設備管理",users:"ユーザー設定",calendar:"会社カレンダー",actuals:"作業実績"};
export default function Management({initialData,role,section,productId,basePath="/workspace",demo=false}:{initialData:PlanData;role:"admin"|"operator";section:string;productId?:string;basePath?:string;demo?:boolean}){
 const [registerUser,setRegisterUser]=useState(false);const [data,setData]=useState(initialData);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [edit,setEdit]=useState<{entity:Entity;row:EditRow}|null>(null);const [confirmation,setConfirmation]=useState<{entity:Entity;row:EditRow;label:string}|null>(null);const [seedConfirm,setSeedConfirm]=useState(false);const [showHidden,setShowHidden]=useState(false);const [importRows,setImportRows]=useState<{date:string;working:boolean;label?:string}[]|null>(null);const router=useRouter();const writable=role==="admin"&&!demo;
 const product=data.products.find(x=>x.id===productId);
 async function save(operation:string,payload:unknown,entity?:string){setBusy(true);setError("");try{const saved=await mutateBusiness(operation,data.revision,payload,entity);setData(saved);setEdit(null);setConfirmation(null);setImportRows(null);setSeedConfirm(false);setNotice("DBに保存しました");router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"保存できませんでした");}finally{setBusy(false);}}
 function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!edit)return;const f=new FormData(event.currentTarget);const id=edit.row.id??(edit.entity==="user"?String(f.get("userId")):undefined);let payload:unknown;
  if(edit.entity==="product")payload={id,name:f.get("name"),customer:f.get("customer"),dueDate:f.get("dueDate"),notes:f.get("notes"),archived:edit.row.archived??false};
  else if(edit.entity==="bom")payload={id,productId:f.get("productId"),name:f.get("name"),kind:f.get("kind"),quantity:Number(f.get("quantity")),notes:f.get("notes"),processes:f.get("kind")==="plate"?PROCESSES.map(x=>x.code):f.getAll("processes"),archived:edit.row.archived??false};
  else if(edit.entity==="equipment")payload={id,name:f.get("name"),process:f.get("process"),active:edit.row.active??true};
  else if(edit.entity==="user")payload={id,name:f.get("name"),role:f.get("role"),active:f.get("active")==="on"};
  else payload={id,name:f.get("name"),quantity:edit.row.quantity,archived:edit.row.archived??false};
  void save("master",payload,edit.entity);
 }
 function buttons(entity:Entity,row:EditRow){const hidden=entity==="equipment"?row.active===false:row.archived;return <div className="row-actions"><button className="button small" disabled={!writable||busy} onClick={()=>setEdit({entity,row})}>編集</button>{entity!=="user"&&<button className="button small" disabled={!writable||busy} onClick={()=>setConfirmation({entity,row,label:hidden?"再表示・再開":"削除（非表示・使用停止）"})}>{hidden?"再表示":"削除"}</button>}</div>;}
 async function importExcel(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);setError("");try{const form=new FormData();form.set("file",file);const response=await fetch("/api/calendar-import",{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);setImportRows(result.days);}catch(cause){setError(cause instanceof Error?cause.message:"Excelを読み込めませんでした");}finally{setBusy(false);event.target.value="";}}
 const bom=data.bom?.filter(x=>(!productId||x.productId===productId)&&(showHidden||!x.archived))??[];
 return <main className="management-page"><header className="management-header"><Link href={basePath}>▦ KPLAN / 生産計画</Link><Link href="/login">ログイン</Link></header><nav className="management-nav">{Object.entries(titles).map(([key,title])=><Link key={key} href={`${basePath}/${key}`} aria-current={section===key?"page":undefined}>{title}</Link>)}</nav><div className="page-heading"><div><div className="eyebrow">{demo?"DEMO":"DATABASE"}</div><h1>{product?.name??titles[section]??"詳細"}</h1><p>{demo?"確認用デモ。DB操作はログイン後に行えます。":"Supabaseのデータを表示しています。変更はDBへ保存されます。"}</p></div><div className="row-actions">{section==="products"&&!productId&&<button className="button primary" disabled={!writable} onClick={()=>setEdit({entity:"product",row:{}})}>＋ 金型を登録</button>}{(section==="bom"||productId)&&<button className="button primary" disabled={!writable} onClick={()=>setEdit({entity:"bom",row:{productId:productId??data.products.find(x=>!x.archived)?.id,kind:"part",quantity:1,processes:["machining"]}})}>＋ BOM項目を登録</button>}{section==="equipment"&&<button className="button primary" disabled={!writable} onClick={()=>setEdit({entity:"equipment",row:{process:"wire"}})}>＋ 設備を登録</button>}{section==="users"&&<button className="button primary" disabled={!writable} onClick={()=>setRegisterUser(true)}>＋ 利用者を登録</button>}<Link className="button" href={basePath}>ガントへ戻る</Link></div></div>
 {error&&<div className="inline-error" role="alert">{error}</div>}{notice&&<div className="message success" role="status">{notice}</div>}{busy&&<p role="status">処理中…</p>}
 {!demo&&role==="admin"&&<details className="setup-tools"><summary>初期セットアップ・テストデータ</summary><p>既存データを消さず、テスト金型・BOM・設備・カレンダーを追加します。BOMから予定を登録して操作できます。</p><button className="button" disabled={busy} onClick={()=>setSeedConfirm(true)}>テストデータを登録</button></details>}
 <label className="checkbox"><input type="checkbox" checked={showHidden} onChange={e=>setShowHidden(e.target.checked)} />非表示・停止中も表示</label>
 {section==="products"&&!productId&&<div className="entity-grid">{data.products.filter(x=>showHidden||!x.archived).map(x=><article key={x.id} className="entity-card"><Link href={`${basePath}/products/${x.id}`}><h2>{x.name}</h2></Link><p>{x.customer||"取引先未登録"} / 納期 {x.dueDate}</p><p>{x.notes}</p>{x.archived&&<span>非表示</span>}{buttons("product",x)}<Link href={`${basePath}/bom?product=${x.id}`}>BOMを設定 →</Link></article>)}</div>}
 {product&&<><section className="entity-card"><h2>金型情報</h2><p>{product.customer} / 納期 {product.dueDate}</p><p>{product.notes}</p>{buttons("product",product)}<Link className="button" href={`${basePath}/bom?product=${product.id}`}>BOM設定</Link></section><h2>製作ロット</h2><table className="management-table"><thead><tr><th>名称</th><th>数量</th><th>工程</th><th>操作</th></tr></thead><tbody>{data.parts.filter(x=>x.productId===product.id&&(showHidden||!x.archived)).map(x=><tr key={x.id}><td>{x.name}{x.archived&&"（取消）"}</td><td>{x.quantity}</td><td>{x.processes?.map(code=>PROCESSES.find(p=>p.code===code)?.name).join(" → ")}</td><td>{buttons("part",x)}</td></tr>)}</tbody></table></>}
 {(section==="bom"||productId)&&<><h2>必要プレート・パーツ</h2><table className="management-table"><thead><tr><th>金型</th><th>名称・区分</th><th>必要 / 登録済み / 未登録</th><th>対象工程</th><th>操作</th></tr></thead><tbody>{bom.map(x=><tr key={x.id}><td>{data.products.find(p=>p.id===x.productId)?.name}</td><td>{x.name} / {x.kind==="plate"?"プレート":"パーツ"}{x.archived&&"（非表示）"}</td><td>{x.quantity} / {x.quantity-remainingQuantity(data,x.id)} / {remainingQuantity(data,x.id)}</td><td>{x.processes.map(code=>PROCESSES.find(p=>p.code===code)?.name).join(" → ")}</td><td>{buttons("bom",x)}<Link href={basePath}>ガントに登録 →</Link></td></tr>)}</tbody></table></>}
 {section==="equipment"&&<div className="entity-grid">{data.equipment.filter(x=>showHidden||x.active!==false).map(x=><article className="entity-card" key={x.id}><Link href={`${basePath}/machines/${x.id}`}><h2>{x.name}</h2></Link><p>{PROCESSES.find(p=>p.code===x.process)?.name}{x.active===false&&" / 停止中"}</p>{buttons("equipment",x)}<Link href={`${basePath}/machines/${x.id}`}>加工予定・加工順 →</Link></article>)}</div>}
 {section==="users"&&<><p className="help-text">「利用者を登録」からメール・パスワードでログインユーザーを作成できます。既存ユーザーの表示名・役割・利用可否は編集できます。</p><table className="management-table"><thead><tr><th>氏名</th><th>役割</th><th>利用可否</th><th>操作</th></tr></thead><tbody>{data.workers.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.role==="admin"?"管理者":"担当者"}</td><td>{x.active===false?"停止":"有効"}</td><td>{buttons("user",x)}</td></tr>)}</tbody></table></>}
 {section==="calendar"&&<><section className="entity-card"><h2>Excel取り込み</h2><p>先頭シートの「日付」「稼働日」列を読み込みます。稼働日は1／0または稼働／休日。内容を確認してから保存します。</p><a className="button" href="/api/calendar-import">Excelテンプレートを取得</a><label>Excelファイル<input type="file" accept=".xlsx" disabled={!writable||busy} onChange={importExcel} /></label></section><table className="management-table"><thead><tr><th>日付</th><th>稼働日</th><th>操作</th></tr></thead><tbody>{Object.entries(data.calendar).sort(([a],[b])=>a.localeCompare(b)).map(([date,working])=><tr key={date}><td>{date}</td><td>{working?"稼働":"休日"}</td><td><button className="button small" disabled={!writable||busy} onClick={()=>void save("master",{days:[{date,working:!working}]},"calendar")}>{working?"休日に変更":"稼働日に変更"}</button></td></tr>)}</tbody></table></>}
 {section==="actuals"&&<table className="management-table"><thead><tr><th>金型・パーツ</th><th>作業者</th><th>開始〜終了</th><th>日別作業時間</th><th>操作</th></tr></thead><tbody>{data.logs.map(x=>{const task=data.tasks.find(t=>t.id===x.taskId);const part=data.parts.find(p=>p.id===task?.partId);return <tr key={x.id}><td>{data.products.find(p=>p.id===part?.productId)?.name} / {part?.name}</td><td>{data.workers.find(w=>w.id===x.workerId)?.name}</td><td>{new Date(x.start).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"})}〜{new Date(x.end).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"})}</td><td><strong>記録 {minutesLabel(x.overrideMinutes??x.calculatedMinutes)}</strong>{x.overrideMinutes!==undefined&&<div>自動計算 {minutesLabel(x.calculatedMinutes)} / 修正理由：{x.reason||"なし"}</div>}<div>日別の自動計算：</div>{workMinutesByDay(x).map(day=><div key={day.date}>{day.date} / {minutesLabel(day.minutes)}</div>)}</td><td><Link className="button small" href={basePath}>ガントから編集</Link><button className="button small" disabled={!writable||busy} onClick={()=>setConfirmation({entity:"part",row:{id:x.id},label:"実績を削除"})}>削除</button></td></tr>;})}</tbody></table>}
 {registerUser&&<div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="ログインユーザーを登録"><div className="panel-header"><h2>ログインユーザーを登録</h2><button className="icon-button" aria-label="閉じる" onClick={()=>setRegisterUser(false)}>×</button></div><LoginUserForm revision={data.revision} onSaved={()=>{setRegisterUser(false);router.refresh();}} /></section></div>}
 {edit&&<div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="登録・編集"><div className="panel-header"><h2>登録・編集</h2><button className="icon-button" onClick={()=>setEdit(null)} aria-label="閉じる">×</button></div>{error&&<div className="inline-error" role="alert">{error}</div>}<form onSubmit={submit}><label>名称<input name="name" defaultValue={edit.row.name??""} required maxLength={120} /></label>{edit.entity==="product"&&<><label>取引先<input name="customer" defaultValue={edit.row.customer??""} maxLength={120} /></label><label>納期<input name="dueDate" type="date" defaultValue={edit.row.dueDate??""} required /></label></>}{edit.entity==="bom"&&<><label>金型<select name="productId" defaultValue={edit.row.productId} required>{data.products.filter(x=>!x.archived).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>区分<select name="kind" defaultValue={edit.row.kind??"part"}><option value="plate">プレート（全5工程）</option><option value="part">パーツ（選択工程）</option></select></label><label>必要数量<input name="quantity" type="number" min={1} defaultValue={edit.row.quantity??1} required /></label><fieldset><legend>パーツの必要工程（プレートは全工程）</legend>{PROCESSES.map(x=><label className="checkbox" key={x.code}><input name="processes" type="checkbox" value={x.code} defaultChecked={edit.row.processes?.includes(x.code)} />{x.name}</label>)}</fieldset></>}{["product","bom"].includes(edit.entity)&&<label>備考<textarea name="notes" defaultValue={edit.row.notes??""} maxLength={2000} /></label>}{edit.entity==="equipment"&&<label>工程<select name="process" defaultValue={edit.row.process??"wire"}>{PROCESSES.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select></label>}{edit.entity==="user"&&<>{!edit.row.id&&<label>AuthアカウントのUUID<input name="userId" required placeholder="Supabase AuthenticationのUID" /></label>}<label>役割<select name="role" defaultValue={edit.row.role??"operator"}><option value="admin">管理者</option><option value="operator">担当者</option></select></label><label className="checkbox"><input name="active" type="checkbox" defaultChecked={edit.row.active!==false} />利用を有効にする</label></>}<div className="modal-actions"><button type="button" className="button" onClick={()=>setEdit(null)}>取消</button><button className="button primary" disabled={busy}>保存</button></div></form></section></div>}
 {(confirmation||seedConfirm)&&<div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="操作の確認"><h2>{confirmation?.label??"テストデータを追加"}しますか？</h2><p>削除は履歴を残します。未着手ロットの取消は数量枠を戻します。</p>{error&&<div className="inline-error">{error}</div>}<div className="modal-actions"><button className="button" onClick={()=>{setConfirmation(null);setSeedConfirm(false);}}>取消</button><button className="button primary" disabled={busy} onClick={()=>{if(seedConfirm)void save("seed",{});else if(confirmation?.label==="実績を削除")void save("deleteActual",{id:confirmation.row.id});else if(confirmation){const {entity,row}=confirmation;void save("master",entity==="equipment"?{id:row.id,name:row.name,process:row.process,active:row.active===false}: {...row,archived:!row.archived},entity);}}}>確認して実行</button></div></section></div>}
 {importRows&&<div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="カレンダー取り込み確認"><h2>{importRows.length}日の設定を取り込み</h2><p>同じ日付の設定を上書きします。取り込み後、ガントで再計算と確認を行ってください。</p><div className="import-preview">{importRows.map(x=><div key={x.date}>{x.date}：{x.working?"稼働":"休日"}</div>)}</div>{error&&<div className="inline-error">{error}</div>}<div className="modal-actions"><button className="button" onClick={()=>setImportRows(null)}>取消</button><button className="button primary" disabled={busy} onClick={()=>void save("master",{days:importRows},"calendar")}>確認して保存</button></div></section></div>}
 </main>;
}
