import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";
import { at, bomProcessCatalog, processCatalog, schedule, type PlanData, type Task } from "../../src/domain/planning.ts";
import { masterSchemas, orderedProcesses } from "../../src/domain/business.ts";
import { ganttRows } from "../../src/domain/gantt-rows.ts";

test("name-only process registration, dynamic BOM, scheduling, CRUD, authorization and rollback",async()=>{
 const db=new PGlite();const admin=randomUUID(),operator=randomUUID();
 try{
  await db.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;");
  for(const file of ["202609300001_initial_schema.sql","202610010001_bom_and_mutations.sql","202610050001_bom_categories.sql","202610050002_bom_names.sql","202610050003_task_days.sql","202610050004_mold_processes.sql","202610050005_press_no.sql","202610070001_trial_next_day.sql"])await db.exec(await readFile(new URL(`../../supabase/migrations/${file}`,import.meta.url),"utf8"));
  await db.query("insert into auth.users values($1),($2)",[admin,operator]);
  await db.query("insert into public.profiles(user_id,display_name,role) values($1,'管理者','admin'),($2,'担当者','operator')",[admin,operator]);
  await db.exec(`set role authenticated;set request.jwt.claim.sub='${admin}'`);
  const read=async()=>(await db.query<{value:PlanData}>("select public.read_planning() value")).rows[0].value;
  await db.query("select public.seed_test_data($1)",[(await read()).revision]);
  const before=await read();
  await db.exec("reset role");
  await db.exec(await readFile(new URL("../../supabase/migrations/202610080001_custom_processes.sql",import.meta.url),"utf8"));
  await db.exec(`set role authenticated;set request.jwt.claim.sub='${admin}'`);
  let data=await read();assert.deepEqual(data.tasks,before.tasks);assert.deepEqual(data.logs,before.logs);
  const save=async(entity:string,payload:unknown,expected?:number)=>db.query("select public.manage_entity($1,$2,$3)",[entity,JSON.stringify(payload),expected??(await read()).revision]);
  const first=randomUUID();const code=`custom_${first}`,secondCode=`custom_${randomUUID()}`;
  // New registrations omit id, as the UI does. A known id is only allowed for edits.
  await save("process",{name:"追加仕上げ",active:true});data=await read();
  const registered=data.processes!.find(p=>p.name==="追加仕上げ")!;
  const equipment=data.equipment.find(e=>e.process===registered.code)!;
  await save("process",{name:"追加検査",active:true});data=await read();
  const next=data.processes!.find(p=>p.name==="追加検査")!;
  assert.deepEqual(bomProcessCatalog(data).slice(-2).map(p=>p.code),[registered.code,next.code]);
  assert.deepEqual(processCatalog(data).slice(-2).map(p=>p.code),["assembly","trial"]);
  assert.deepEqual(orderedProcesses([next.code,"wire",registered.code],data),["wire",registered.code,next.code]);
  const revision=data.revision;
  await assert.rejects(()=>save("process",{name:"追加仕上げ",active:true}),/unique|duplicate/);
  await assert.rejects(()=>save("process",{id:first,name:"不正な編集",active:true}),/登録済み/);
  await assert.rejects(()=>save("process",{name:"",active:true}),/check constraint/);
  assert.equal((await read()).revision,revision);
  await assert.rejects(()=>save("process",{name:"競合",active:true},revision-1),/更新/);
  await db.exec(`set request.jwt.claim.sub='${operator}'`);
  await assert.rejects(()=>save("process",{name:"担当者から追加",active:true}),/管理者/);
  await assert.rejects(()=>db.query("insert into public.process_definitions(code,name,sort_order) values($1,'直接追加',500)",[code]),/permission/);
  await db.exec(`set request.jwt.claim.sub='${admin}'`);
  await save("bomName",{name:"検証用部品",categoryId:"00000000-0000-4000-8000-000000000002",active:true});
  const bomId=randomUUID(),productId=data.products[0].id;
  const bom={id:bomId,productId,categoryId:"00000000-0000-4000-8000-000000000002",name:"検証用部品",kind:"part",quantity:2,notes:"",processes:["wire",registered.code,next.code],archived:false};
  assert.equal(masterSchemas.bom.safeParse(bom).success,true);
  await save("bom",bom);data=await read();assert.deepEqual(data.bom!.find(b=>b.id===bomId)!.processes,bom.processes);
  const plateId=randomUUID();const plateName=data.bomNames!.find(n=>n.categoryId==="00000000-0000-4000-8000-000000000001"&&!data.bom!.some(b=>b.productId===productId&&b.name===n.name))!.name;
  const plate={...bom,id:plateId,categoryId:"00000000-0000-4000-8000-000000000001",kind:"plate",name:plateName,processes:[registered.code]};
  await save("bom",plate);data=await read();assert.deepEqual(data.bom!.find(b=>b.id===plateId)!.processes,["machining","grinding","wire",registered.code]);
  await save("bom",{...plate,notes:"編集後"});data=await read();assert.ok(data.bom!.find(b=>b.id===plateId)!.processes.includes(registered.code));
  await assert.rejects(()=>save("bom",{...bom,processes:[secondCode]}),/未登録/);
  const partId=randomUUID();const tasks:Task[]=bom.processes.map(process=>({id:randomUUID(),partId,process,equipmentId:data.equipment.find(e=>e.process===process&&e.active!==false)!.id,workerId:admin,duration:60,earliestStart:at("2026-10-05",530),priority:100,status:"pending",overnight:false,breakRun:false,fixed:false,plannedStart:"",plannedEnd:"",segments:[]}));
  const candidate:PlanData={...data,parts:[...data.parts,{id:partId,productId,bomId,name:bom.name,quantity:1,drawingNumber:"",processes:bom.processes}],tasks:[...data.tasks,...tasks]};
  candidate.tasks=schedule(candidate,30);
  const newTasks=candidate.tasks.filter(t=>t.partId===partId);
  assert.equal(newTasks.length,3);assert.ok(Date.parse(newTasks[1].plannedStart)>=Date.parse(newTasks[0].plannedEnd));
  assert.deepEqual(ganttRows(newTasks,processCatalog(data)).map(row=>row.tasks[0].process),bom.processes);
  await db.query("select public.commit_plan($1,$2,false)",[JSON.stringify({parts:candidate.parts,tasks:candidate.tasks}),data.revision]);data=await read();
  assert.equal(data.tasks.filter(t=>t.partId===partId).length,3);
  const wrong=structuredClone(data);const moved=wrong.tasks.find(t=>t.partId===partId&&t.process===registered.code)!;
  moved.plannedStart=at("2026-10-01",540);moved.plannedEnd=at("2026-10-01",600);moved.segments=[{start:moved.plannedStart,end:moved.plannedEnd}];
  await assert.rejects(()=>db.query("select public.commit_plan($1,$2,true)",[JSON.stringify({parts:wrong.parts,tasks:wrong.tasks}),data.revision]),/先行工程/);
  assert.equal((await read()).revision,data.revision);
  await save("process",{id:equipment.id,name:"追加仕上げ改",active:true});data=await read();
  assert.equal(data.processes!.find(p=>p.code===registered.code)!.name,"追加仕上げ改");assert.equal(data.equipment.find(e=>e.id===equipment.id)!.name,"追加仕上げ改");
  await assert.rejects(()=>save("process",{id:equipment.id,name:"追加仕上げ改",active:false}),/未完了/);
  const extra=data.equipment.find(e=>e.process===next.code)!;
  assert.ok(extra);assert.equal((await read()).processes!.find(p=>p.code===registered.code)!.active,true);
  await save("process",{name:"停止工程",active:true});data=await read();
  const stoppable=data.equipment.find(e=>e.name==="停止工程")!;
  await save("process",{id:stoppable.id,name:"停止工程",active:false});
  await assert.rejects(()=>save("bom",{...bom,id:randomUUID(),processes:[stoppable.process]}),/有効な登録済み/);
  await save("process",{id:stoppable.id,name:"停止工程",active:true});
  assert.equal((await read()).processes!.find(p=>p.code===stoppable.process)!.active,true);
 }finally{await db.close();}
});
